name: ten
description: "A set of Flutter component libraries based on UX-first principles"
version: 0.0.9
homepage: https://github.com/lm83680/ten

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  cached_network_image: ^3.4.0 #缓存网络图像图片

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.18.2

flutter:
  assets:
    - lib/assets/